In [1]:
import numpy as np
import pandas as pd

In [2]:
DS = pd.read_csv("HFCRD.csv")

In [3]:
DS.isnull().any()

age                         False
anaemia                     False
creatinine_phosphokinase    False
diabetes                    False
ejection_fraction           False
high_blood_pressure         False
platelets                   False
serum_creatinine            False
serum_sodium                False
sex                         False
smoking                     False
time                        False
DEATH_EVENT                 False
dtype: bool

In [4]:
x = DS.iloc[:,0:11]
y = DS.iloc[:,12]
x

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
5    90.0        1                        47         0                 40   
6    75.0        1                       246         0                 15   
7    60.0        1                       315         1                 60   
8    65.0        0                       157         0                 65   
9    80.0        1                       123         0                 35   
10   75.0        1                        81         0                 38   
11   62.0        0                       231         0                 25   
12   45.0        1                       981         0                 30   
13   50.0        1                       168         0                 38   
14   49.0        1                        80         0                 30   
15   82.0        1                       379         0                 50   
16   87.0        1                       149         0                 38   
17   45.0        0                       582         0                 14   
18   70.0        1                       125         0                 25   
19   48.0        1                       582         1                 55   
20   65.0        1                        52         0                 25   
21   65.0        1                       128         1                 30   
22   68.0        1                       220         0                 35   
23   53.0        0                        63         1                 60   
24   75.0        0                       582         1                 30   
25   80.0        0                       148         1                 38   
26   95.0        1                       112         0                 40   
27   70.0        0                       122         1                 45   
28   58.0        1                        60         0                 38   
29   82.0        0                        70         1                 30   
..    ...      ...                       ...       ...                ...   
269  40.0        0                       582         1                 35   
270  44.0        0                       582         1                 30   
271  51.0        0                       582         1                 40   
272  67.0        0                       213         0                 38   
273  42.0        0                        64         0                 40   
274  60.0        1                       257         1                 30   
275  45.0        0                       582         0                 38   
276  70.0        0                       618         0                 35   
277  70.0        0                       582         1                 38   
278  50.0        1                      1051         1                 30   
279  55.0        0                        84         1                 38   
280  70.0        0                      2695         1                 40   
281  70.0        0                       582         0                 40   
282  42.0        0                        64         0                 30   
283  65.0        0                      1688         0                 38   
284  50.0        1                        54         0                 40   
285  55.0        1                       170         1                 40   
286  60.0        0                       253         0                 35   
287  45.0        0                       582         1                 55   
288  65.0        0                       892         1                 35   
28

In [5]:
x = DS.iloc[:,0:11].values
y = DS.iloc[:,12].values

In [6]:
x.shape

(299, 11)

In [7]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtyp

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
DS["DEATH_EVENT"]=le.fit_transform(DS["DEATH_EVENT"])

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [12]:
model = Sequential()

In [13]:
model.add(Dense(11,kernel_initializer = "uniform", activation ="relu"))

In [14]:
model.add(Dense(22,kernel_initializer = "uniform", activation ="relu"))

In [15]:
model.add(Dense(44,kernel_initializer = "uniform", activation ="relu"))

In [16]:
model.add(Dense(1,kernel_initializer = "uniform", activation ="sigmoid"))

In [17]:
model.compile("adam","binary_crossentropy",metrics = ["accuracy"])

In [18]:
model.fit(x_train,y_train,batch_size = 16, epochs=400)

Epoch 1/400
15/15 [==============================] - 1s 3ms/step - loss: 0.6912 - accuracy: 0.6611
Epoch 2/400
15/15 [==============================] - 0s 3ms/step - loss: 0.6843 - accuracy: 0.6946
Epoch 3/400
15/15 [==============================] - 0s 3ms/step - loss: 0.6719 - accuracy: 0.6946
Epoch 4/400
15/15 [==============================] - 0s 3ms/step - loss: 0.6425 - accuracy: 0.6946
Epoch 5/400
15/15 [==============================] - 0s 3ms/step - loss: 0.5948 - accuracy: 0.6946
Epoch 6/400
15/15 [==============================] - 0s 3ms/step - loss: 0.5521 - accuracy: 0.6946
Epoch 7/400
15/15 [==============================] - 0s 3ms/step - loss: 0.5259 - accuracy: 0.6946
Epoch 8/400
15/15 [==============================] - 0s 3ms/step - loss: 0.5095 - accuracy: 0.6946
Epoch 9/400
15/15 [==============================] - 0s 3ms/step - loss: 0.4962 - accuracy: 0.7071
Epoch 10/400
15/15 [==============================] - 0s 3ms/step - loss: 0.4890 - accuracy: 0.7490
Epoch 11/

15/15 [==============================] - 0s 3ms/step - loss: 0.3051 - accuracy: 0.8870
Epoch 84/400
15/15 [==============================] - 0s 3ms/step - loss: 0.3036 - accuracy: 0.8787
Epoch 85/400
15/15 [==============================] - 0s 3ms/step - loss: 0.2944 - accuracy: 0.8912
Epoch 86/400
15/15 [==============================] - 0s 3ms/step - loss: 0.2950 - accuracy: 0.8954
Epoch 87/400
15/15 [==============================] - 0s 3ms/step - loss: 0.2910 - accuracy: 0.8954
Epoch 88/400
15/15 [==============================] - 0s 3ms/step - loss: 0.2933 - accuracy: 0.8996
Epoch 89/400
15/15 [==============================] - 0s 3ms/step - loss: 0.2903 - accuracy: 0.8912
Epoch 90/400
15/15 [==============================] - 0s 3ms/step - loss: 0.2875 - accuracy: 0.8954
Epoch 91/400
15/15 [==============================] - 0s 3ms/step - loss: 0.2844 - accuracy: 0.9038
Epoch 92/400
15/15 [==============================] - 0s 3ms/step - loss: 0.2835 - accuracy: 0.8996
Epoch 93/400


15/15 [==============================] - 0s 3ms/step - loss: 0.1784 - accuracy: 0.9331
Epoch 165/400
15/15 [==============================] - 0s 3ms/step - loss: 0.1695 - accuracy: 0.9414
Epoch 166/400
15/15 [==============================] - 0s 3ms/step - loss: 0.1698 - accuracy: 0.9414
Epoch 167/400
15/15 [==============================] - 0s 4ms/step - loss: 0.1637 - accuracy: 0.9414
Epoch 168/400
15/15 [==============================] - 0s 3ms/step - loss: 0.1630 - accuracy: 0.9414
Epoch 169/400
15/15 [==============================] - 0s 3ms/step - loss: 0.1630 - accuracy: 0.9414
Epoch 170/400
15/15 [==============================] - 0s 3ms/step - loss: 0.1643 - accuracy: 0.9414
Epoch 171/400
15/15 [==============================] - 0s 3ms/step - loss: 0.1609 - accuracy: 0.9456
Epoch 172/400
15/15 [==============================] - 0s 3ms/step - loss: 0.1624 - accuracy: 0.9372
Epoch 173/400
15/15 [==============================] - 0s 3ms/step - loss: 0.1630 - accuracy: 0.9372
Epoc

15/15 [==============================] - 0s 3ms/step - loss: 0.1086 - accuracy: 0.9331
Epoch 246/400
15/15 [==============================] - 0s 3ms/step - loss: 0.1108 - accuracy: 0.9414
Epoch 247/400
15/15 [==============================] - 0s 3ms/step - loss: 0.0984 - accuracy: 0.9456
Epoch 248/400
15/15 [==============================] - 0s 3ms/step - loss: 0.1039 - accuracy: 0.9456
Epoch 249/400
15/15 [==============================] - 0s 4ms/step - loss: 0.1024 - accuracy: 0.9414
Epoch 250/400
15/15 [==============================] - 0s 3ms/step - loss: 0.1150 - accuracy: 0.9456
Epoch 251/400
15/15 [==============================] - 0s 3ms/step - loss: 0.0935 - accuracy: 0.9498
Epoch 252/400
15/15 [==============================] - 0s 3ms/step - loss: 0.0866 - accuracy: 0.9498
Epoch 253/400
15/15 [==============================] - 0s 3ms/step - loss: 0.0861 - accuracy: 0.9498
Epoch 254/400
15/15 [==============================] - 0s 3ms/step - loss: 0.0845 - accuracy: 0.9498
Epoc

15/15 [==============================] - 0s 3ms/step - loss: 0.0355 - accuracy: 0.9958
Epoch 327/400
15/15 [==============================] - 0s 3ms/step - loss: 0.0353 - accuracy: 0.9958
Epoch 328/400
15/15 [==============================] - 0s 3ms/step - loss: 0.0358 - accuracy: 1.0000
Epoch 329/400
15/15 [==============================] - 0s 4ms/step - loss: 0.0350 - accuracy: 1.0000
Epoch 330/400
15/15 [==============================] - 0s 3ms/step - loss: 0.0353 - accuracy: 0.9958
Epoch 331/400
15/15 [==============================] - 0s 3ms/step - loss: 0.0348 - accuracy: 1.0000
Epoch 332/400
15/15 [==============================] - 0s 3ms/step - loss: 0.0341 - accuracy: 1.0000
Epoch 333/400
15/15 [==============================] - 0s 3ms/step - loss: 0.0336 - accuracy: 1.0000
Epoch 334/400
15/15 [==============================] - 0s 3ms/step - loss: 0.0333 - accuracy: 1.0000
Epoch 335/400
15/15 [==============================] - 0s 3ms/step - loss: 0.0340 - accuracy: 1.0000
Epoc

In [28]:
TEST = model.predict_classes(sc.transform([[94,0,582,1,38,1,263358.03,1.83,134,1,0,]]))
TEST


C:\Users\Kalyan\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[1]])

In [29]:
TEST = model.predict_classes(sc.transform([[60,0,2656,1,30,0,305000,2.3,137,1,0]]))
TEST

C:\Users\Kalyan\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[1]])

In [30]:
TEST = model.predict_classes(sc.transform([[70,0,582,0,20,1,263358.03,1.83,134,1,1]]))
TEST

C:\Users\Kalyan\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[1]])

In [31]:
TEST = model.predict_classes(sc.transform([[72,0,127,1,50,1,218000,1,134,1,0]]))
TEST

C:\Users\Kalyan\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0]])

In [32]:
TEST = model.predict_classes(sc.transform([[60,0,582,1,38,1,451000,0.6,138,1,1]]))
TEST

C:\Users\Kalyan\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[1]])

In [33]:
TEST = model.predict_classes(sc.transform([[70,1,75,0,35,0,223000,2.7,138,1,1]]))
TEST

C:\Users\Kalyan\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0]])

0 1 0 1 0

1 1 0 1 0

In [25]:
ypred = model.predict(x_test)

In [26]:
ypred

array([[4.1584225e-09],
       [4.9180118e-03],
       [9.1336966e-01],
       [2.4086699e-10],
       [6.8515888e-04],
       [9.9986017e-01],
       [9.9993873e-01],
       [2.3148480e-07],
       [7.2424293e-01],
       [8.5244160e-08],
       [7.3344346e-15],
       [5.8868015e-11],
       [5.1888810e-03],
       [9.2326659e-01],
       [2.7724594e-02],
       [9.9991012e-01],
       [3.0334591e-14],
       [4.3560821e-03],
       [9.2096180e-09],
       [7.4819475e-01],
       [3.1384379e-03],
       [1.0349518e-08],
       [2.9385433e-01],
       [3.2613990e-01],
       [3.2613990e-01],
       [1.4821602e-01],
       [9.9990416e-01],
       [1.2920706e-06],
       [5.7207295e-08],
       [2.3822547e-08],
       [2.5981304e-05],
       [3.2613990e-01],
       [1.3923231e-03],
       [4.0932315e-14],
       [5.9560484e-14],
       [1.0890482e-02],
       [1.8567592e-13],
       [1.5232615e-01],
       [1.5611305e-14],
       [1.3259377e-07],
       [4.0557176e-01],
       [8.939856