In [1]:
import numpy as np
import pandas as pd

In [2]:
DS = pd.read_csv("HFCRD.csv")

In [3]:
DS.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [4]:
DS.isnull().any()

age                         False
anaemia                     False
creatinine_phosphokinase    False
diabetes                    False
ejection_fraction           False
high_blood_pressure         False
platelets                   False
serum_creatinine            False
serum_sodium                False
sex                         False
smoking                     False
time                        False
DEATH_EVENT                 False
dtype: bool

In [5]:
DS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
age                         299 non-null float64
anaemia                     299 non-null int64
creatinine_phosphokinase    299 non-null int64
diabetes                    299 non-null int64
ejection_fraction           299 non-null int64
high_blood_pressure         299 non-null int64
platelets                   299 non-null float64
serum_creatinine            299 non-null float64
serum_sodium                299 non-null int64
sex                         299 non-null int64
smoking                     299 non-null int64
time                        299 non-null int64
DEATH_EVENT                 299 non-null int64
dtypes: float64(3), int64(10)
memory usage: 30.4 KB


In [6]:
DS.describe()

age     anaemia  creatinine_phosphokinase    diabetes  \
count  299.000000  299.000000                299.000000  299.000000   
mean    60.833893    0.431438                581.839465    0.418060   
std     11.894809    0.496107                970.287881    0.494067   
min     40.000000    0.000000                 23.000000    0.000000   
25%     51.000000    0.000000                116.500000    0.000000   
50%     60.000000    0.000000                250.000000    0.000000   
75%     70.000000    1.000000                582.000000    1.000000   
max     95.000000    1.000000               7861.000000    1.000000   

       ejection_fraction  high_blood_pressure      platelets  \
count         299.000000           299.000000     299.000000   
mean           38.083612             0.351171  263358.029264   
std            11.834841             0.478136   97804.236869   
min            14.000000             0.000000   25100.000000   
25%            30.000000             0.000000  212500.000000   
50%            38.000000             0.000000  262000.000000   
75%            45.000000             1.000000  303500.000000   
max            80.000000             1.000000  850000.000000   

       serum_creatinine  serum_sodium         sex    smoking        time  \
count         299.00000    299.000000  299.000000  299.00000  299.000000   
mean            1.39388    136.625418    0.648829    0.32107  130.260870   
std             1.03451      4.412477    0.478136    0.46767   77.614208   
min             0.50000    113.000000    0.000000    0.00000    4.000000   
25%             0.90000    134.000000    0.000000    0.00000   73.000000   
50%             1.10000    137.000000    1.000000    0.00000  115.000000   
75%             1.40000    140.000000    1.000000    1.00000  203.000000   
max             9.40000    148.000000    1.000000    1.00000  285.000000   

       DEATH_EVENT  
count    299.00000  
mean       0.32107  
std        0.46767  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        1.00000  
max        1.00000

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
DS["DEATH_EVENT"] = le.fit_transform(DS["DEATH_EVENT"])
DS["DEATH_EVENT"]

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     0
15     1
16     1
17     1
18     1
19     1
20     0
21     1
22     1
23     0
24     1
25     1
26     1
27     1
28     1
29     1
      ..
269    0
270    0
271    0
272    0
273    0
274    0
275    0
276    0
277    0
278    0
279    0
280    0
281    0
282    0
283    0
284    0
285    0
286    0
287    0
288    0
289    0
290    0
291    0
292    0
293    0
294    0
295    0
296    0
297    0
298    0
Name: DEATH_EVENT, Length: 299, dtype: int64

In [8]:
x = DS.iloc[:,0:11]
x

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
5    90.0        1                        47         0                 40   
6    75.0        1                       246         0                 15   
7    60.0        1                       315         1                 60   
8    65.0        0                       157         0                 65   
9    80.0        1                       123         0                 35   
10   75.0        1                        81         0                 38   
11   62.0        0                       231         0                 25   
12   45.0        1                       981         0                 30   
13   50.0        1                       168         0                 38   
14   49.0        1                        80         0                 30   
15   82.0        1                       379         0                 50   
16   87.0        1                       149         0                 38   
17   45.0        0                       582         0                 14   
18   70.0        1                       125         0                 25   
19   48.0        1                       582         1                 55   
20   65.0        1                        52         0                 25   
21   65.0        1                       128         1                 30   
22   68.0        1                       220         0                 35   
23   53.0        0                        63         1                 60   
24   75.0        0                       582         1                 30   
25   80.0        0                       148         1                 38   
26   95.0        1                       112         0                 40   
27   70.0        0                       122         1                 45   
28   58.0        1                        60         0                 38   
29   82.0        0                        70         1                 30   
..    ...      ...                       ...       ...                ...   
269  40.0        0                       582         1                 35   
270  44.0        0                       582         1                 30   
271  51.0        0                       582         1                 40   
272  67.0        0                       213         0                 38   
273  42.0        0                        64         0                 40   
274  60.0        1                       257         1                 30   
275  45.0        0                       582         0                 38   
276  70.0        0                       618         0                 35   
277  70.0        0                       582         1                 38   
278  50.0        1                      1051         1                 30   
279  55.0        0                        84         1                 38   
280  70.0        0                      2695         1                 40   
281  70.0        0                       582         0                 40   
282  42.0        0                        64         0                 30   
283  65.0        0                      1688         0                 38   
284  50.0        1                        54         0                 40   
285  55.0        1                       170         1                 40   
286  60.0        0                       253         0                 35   
287  45.0        0                       582         1                 55   
288  65.0        0                       892         1                 35   
28

In [9]:
x = DS.iloc[:,0:11].values
y = DS.iloc[:,12].values

In [10]:
# y = pd.factorize(DS['DEATH_EVENT'])[0].reshape(-1, 1)

In [11]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtyp

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [13]:
y_test

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1], dtype=int64)

In [14]:
from sklearn.preprocessing import StandardScaler
SC = StandardScaler()
xtrain = SC.fit_transform(x_train)
xtest = SC.fit_transform(x_test)


In [15]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x_train,y_train)

C:\Users\Kalyan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
ypred = logreg.predict(x_test)

In [17]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(ypred,y_test)

In [18]:
accuracy

0.7666666666666667

In [19]:
TEST = logreg.predict(SC.transform([[55,0,7861,0,38,0,263358.03,1.1,136,1,0]]))

In [20]:
TEST

array([0], dtype=int64)

In [21]:
TEST = logreg.predict(SC.transform([[65,0,146,0,20,0,162000,1.3,129,1,1]]))
TEST

array([1], dtype=int64)

In [22]:
TEST = logreg.predict(SC.transform([[49,1,80,0,30,1,427000,1,138,0,0]]))
TEST

array([0], dtype=int64)