In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
DS = pd.read_csv("placement.csv")

In [4]:
DS.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [5]:
DS.isnull().any()

sl_no             False
gender            False
ssc_p             False
ssc_b             False
hsc_p             False
hsc_b             False
hsc_s             False
degree_p          False
degree_t          False
workex            False
etest_p           False
specialisation    False
mba_p             False
status            False
salary             True
dtype: bool

In [6]:
DS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
sl_no             215 non-null int64
gender            215 non-null object
ssc_p             215 non-null float64
ssc_b             215 non-null object
hsc_p             215 non-null float64
hsc_b             215 non-null object
hsc_s             215 non-null object
degree_p          215 non-null float64
degree_t          215 non-null object
workex            215 non-null object
etest_p           215 non-null float64
specialisation    215 non-null object
mba_p             215 non-null float64
status            215 non-null object
salary            148 non-null float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB


# ONE HOT ENCODING

### 1 3 5 6 8 9 11


In [7]:
DS['salary'].isna().sum()

67

In [8]:
DS['salary'].fillna(0,inplace=True)
# DS['salary'].fillna(DS['salary'].mean(),inplace=True)
# DS['salary'].fillna(DS['salary'].median(),inplace=True)
DS

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00   
1        2      M  79.33  Central  78.33   Others   Science     77.48   
2        3      M  65.00  Central  68.00  Central      Arts     64.00   
3        4      M  56.00  Central  52.00  Central   Science     52.00   
4        5      M  85.80  Central  73.60  Central  Commerce     73.30   
5        6      M  55.00   Others  49.80   Others   Science     67.25   
6        7      F  46.00   Others  49.20   Others  Commerce     79.00   
7        8      M  82.00  Central  64.00  Central   Science     66.00   
8        9      M  73.00  Central  79.00  Central  Commerce     72.00   
9       10      M  58.00  Central  70.00  Central  Commerce     61.00   
10      11      M  58.00  Central  61.00  Central  Commerce     60.00   
11      12      M  69.60  Central  68.40  Central  Commerce     78.30   
12      13      F  47.00  Central  55.00   Others   Science     65.00   
13      14      F  77.00  Central  87.00  Central  Commerce     59.00   
14      15      M  62.00  Central  47.00  Central  Commerce     50.00   
15      16      F  65.00  Central  75.00  Central  Commerce     69.00   
16      17      M  63.00  Central  66.20  Central  Commerce     65.60   
17      18      F  55.00  Central  67.00  Central  Commerce     64.00   
18      19      F  63.00  Central  66.00  Central  Commerce     64.00   
19      20      M  60.00   Others  67.00   Others      Arts     70.00   
20      21      M  62.00   Others  65.00   Others  Commerce     66.00   
21      22      F  79.00   Others  76.00   Others  Commerce     85.00   
22      23      F  69.80   Others  60.80   Others   Science     72.23   
23      24      F  77.40   Others  60.00   Others   Science     64.74   
24      25      M  76.50   Others  97.70   Others   Science     78.86   
25      26      F  52.58   Others  54.60  Central  Commerce     50.20   
26      27      M  71.00   Others  79.00   Others  Commerce     66.00   
27      28      M  63.00   Others  67.00   Others  Commerce     66.00   
28      29      M  76.76   Others  76.50   Others  Commerce     67.50   
29      30      M  62.00  Central  67.00  Central  Commerce     58.00   
..     ...    ...    ...      ...    ...      ...       ...       ...   
185    186      F  88.00  Central  72.00  Central   Science     78.00   
186    187      F  52.00  Central  64.00  Central  Commerce     61.00   
187    188      M  78.50  Central  65.50  Central   Science     67.00   
188    189      M  61.80   Others  47.00   Others  Commerce     54.38   
189    190      F  54.00  Central  77.60   Others  Commerce     69.20   
190    191      F  64.00   Others  70.20  Central  Commerce     61.00   
191    192      M  67.00   Others  61.00  Central   Science     72.00   
192    193      M  65.20  Central  61.40  Central  Commerce     64.80   
193    194      F  60.00  Central  63.00  Central      Arts     56.00   
194    195      M  52.00   Others  55.00   Others  Commerce     56.30   
195    196      M  66.00  Central  76.00  Central  Commerce     72.00   
196    197      M  72.00   Others  63.00   Others   Science     77.50   
197    198      F  83.96   Others  53.00   Others   Science     91.00   
198    199      F  67.00  Central  70.00  Central  Commerce     65.00   
199    200      M  69.00   Others  65.00   Others  Commerce     57.00   
200    201      M  69.00   Others  60.00   Others  Commerce     65.00   
201    202      M  54.20  Central  63.00   Others   Science     58.00   
202    203      M  70.00  Central  63.00  Central   Science     66.00   
203    204      M  55.68   Others  61.33   Others  Commerce     56.87   
204    205      F  74.00   Others  73.00   Others  Commerce     73.00   
205    206      M  61.00   Others  62.00   Others  Commerce     65.00   
206    207      M  41.00  Central  42.00  Central   Science     60.00   
207    208      M  83.33  Central  78.00   Others  Commerce    

In [9]:
DS["ssc_b"].unique()

array(['Others', 'Central'], dtype=object)

In [10]:
DS["hsc_s"].unique()

array(['Commerce', 'Science', 'Arts'], dtype=object)

In [11]:
DS["degree_t"].unique()

array(['Sci&Tech', 'Comm&Mgmt', 'Others'], dtype=object)

In [12]:
DS["specialisation"].unique()

array(['Mkt&HR', 'Mkt&Fin'], dtype=object)

In [13]:
DS.shape

(215, 15)

In [14]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# DS["status"] = le.fit_transform(DS["status"])

In [15]:
x = DS.iloc[:,1:14]

In [16]:
x

gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p   degree_t  \
0        M  67.00   Others  91.00   Others  Commerce     58.00   Sci&Tech   
1        M  79.33  Central  78.33   Others   Science     77.48   Sci&Tech   
2        M  65.00  Central  68.00  Central      Arts     64.00  Comm&Mgmt   
3        M  56.00  Central  52.00  Central   Science     52.00   Sci&Tech   
4        M  85.80  Central  73.60  Central  Commerce     73.30  Comm&Mgmt   
5        M  55.00   Others  49.80   Others   Science     67.25   Sci&Tech   
6        F  46.00   Others  49.20   Others  Commerce     79.00  Comm&Mgmt   
7        M  82.00  Central  64.00  Central   Science     66.00   Sci&Tech   
8        M  73.00  Central  79.00  Central  Commerce     72.00  Comm&Mgmt   
9        M  58.00  Central  70.00  Central  Commerce     61.00  Comm&Mgmt   
10       M  58.00  Central  61.00  Central  Commerce     60.00  Comm&Mgmt   
11       M  69.60  Central  68.40  Central  Commerce     78.30  Comm&Mgmt   
12       F  47.00  Central  55.00   Others   Science     65.00  Comm&Mgmt   
13       F  77.00  Central  87.00  Central  Commerce     59.00  Comm&Mgmt   
14       M  62.00  Central  47.00  Central  Commerce     50.00  Comm&Mgmt   
15       F  65.00  Central  75.00  Central  Commerce     69.00  Comm&Mgmt   
16       M  63.00  Central  66.20  Central  Commerce     65.60  Comm&Mgmt   
17       F  55.00  Central  67.00  Central  Commerce     64.00  Comm&Mgmt   
18       F  63.00  Central  66.00  Central  Commerce     64.00  Comm&Mgmt   
19       M  60.00   Others  67.00   Others      Arts     70.00  Comm&Mgmt   
20       M  62.00   Others  65.00   Others  Commerce     66.00  Comm&Mgmt   
21       F  79.00   Others  76.00   Others  Commerce     85.00  Comm&Mgmt   
22       F  69.80   Others  60.80   Others   Science     72.23   Sci&Tech   
23       F  77.40   Others  60.00   Others   Science     64.74   Sci&Tech   
24       M  76.50   Others  97.70   Others   Science     78.86   Sci&Tech   
25       F  52.58   Others  54.60  Central  Commerce     50.20  Comm&Mgmt   
26       M  71.00   Others  79.00   Others  Commerce     66.00  Comm&Mgmt   
27       M  63.00   Others  67.00   Others  Commerce     66.00  Comm&Mgmt   
28       M  76.76   Others  76.50   Others  Commerce     67.50  Comm&Mgmt   
29       M  62.00  Central  67.00  Central  Commerce     58.00  Comm&Mgmt   
..     ...    ...      ...    ...      ...       ...       ...        ...   
185      F  88.00  Central  72.00  Central   Science     78.00     Others   
186      F  52.00  Central  64.00  Central  Commerce     61.00  Comm&Mgmt   
187      M  78.50  Central  65.50  Central   Science     67.00   Sci&Tech   
188      M  61.80   Others  47.00   Others  Commerce     54.38  Comm&Mgmt   
189      F  54.00  Central  77.60   Others  Commerce     69.20  Comm&Mgmt   
190      F  64.00   Others  70.20  Central  Commerce     61.00  Comm&Mgmt   
191      M  67.00   Others  61.00  Central   Science     72.00  Comm&Mgmt   
192      M  65.20  Central  61.40  Central  Commerce     64.80  Comm&Mgmt   
193      F  60.00  Central  63.00  Central      Arts     56.00     Others   
194      M  52.00   Others  55.00   Others  Commerce     56.30  Comm&Mgmt   
195      M  66.00  Central  76.00  Central  Commerce     72.00  Comm&Mgmt   
196      M  72.00   Others  63.00   Others   Science     77.50   Sci&Tech   
197      F  83.96   Others  53.00   Others   Science     91.00   Sci&Tech   
198      F  67.00  Central  70.00  Central  Commerce     65.00     Others   
199      M  69.00   Others  65.00   Others  Commerce     57.00  Comm&Mgmt   
200      M  69.00   Others  60.00   Others  Commerce     65.00  Comm&Mgmt   
201      M  54.20  Central  63.00   Others   Science     58.00  Comm&Mgmt   
202      M  70.00  Central  63.00  Central   Science     66.00   Sci&Tech   
203      M  55.68   Others  61.33   Others  Commerce     56.87  Comm&Mgmt   
204      F  74.00   Others  73.00   Others  Commerce     73.00  Comm&Mgmt   


In [17]:
x.shape

(215, 13)

In [18]:
y = DS.iloc[:,14].values
y

array([270000., 200000., 250000.,      0., 425000.,      0.,      0.,
       252000., 231000.,      0., 260000., 250000.,      0., 218000.,
            0., 200000., 300000.,      0.,      0., 236000., 265000.,
       393000., 360000., 300000., 360000.,      0., 240000., 265000.,
       350000.,      0., 250000.,      0., 278000., 260000.,      0.,
       300000.,      0., 320000., 240000., 411000., 287000.,      0.,
            0., 300000., 200000.,      0.,      0., 204000., 250000.,
            0., 200000.,      0.,      0., 450000., 216000., 220000.,
       240000., 360000., 268000., 265000., 260000., 300000., 240000.,
            0., 240000.,      0., 275000., 275000.,      0., 275000.,
       360000., 240000., 240000., 218000., 336000.,      0., 230000.,
       500000., 270000.,      0., 240000., 300000.,      0., 300000.,
       300000., 400000., 220000.,      0., 210000., 210000., 300000.,
            0., 230000.,      0., 260000., 420000., 300000.,      0.,
       220000.,     

In [19]:
DS.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       0.0  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [20]:
x.shape

(215, 13)

In [21]:
DS.iloc[:,[1,3,5,6,8,9,11,12]]

gender    ssc_b    hsc_b     hsc_s   degree_t workex specialisation  mba_p
0        M   Others   Others  Commerce   Sci&Tech     No         Mkt&HR  58.80
1        M  Central   Others   Science   Sci&Tech    Yes        Mkt&Fin  66.28
2        M  Central  Central      Arts  Comm&Mgmt     No        Mkt&Fin  57.80
3        M  Central  Central   Science   Sci&Tech     No         Mkt&HR  59.43
4        M  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin  55.50
5        M   Others   Others   Science   Sci&Tech    Yes        Mkt&Fin  51.58
6        F   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin  53.29
7        M  Central  Central   Science   Sci&Tech    Yes        Mkt&Fin  62.14
8        M  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin  61.29
9        M  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin  52.21
10       M  Central  Central  Commerce  Comm&Mgmt    Yes         Mkt&HR  60.85
11       M  Central  Central  Commerce  Comm&Mgmt    Yes        Mkt&Fin  63.70
12       F  Central   Others   Science  Comm&Mgmt     No         Mkt&HR  65.04
13       F  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin  68.63
14       M  Central  Central  Commerce  Comm&Mgmt     No         Mkt&HR  54.96
15       F  Central  Central  Commerce  Comm&Mgmt    Yes        Mkt&Fin  64.66
16       M  Central  Central  Commerce  Comm&Mgmt    Yes        Mkt&Fin  62.54
17       F  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin  67.28
18       F  Central  Central  Commerce  Comm&Mgmt     No         Mkt&HR  64.08
19       M   Others   Others      Arts  Comm&Mgmt    Yes        Mkt&Fin  77.89
20       M   Others   Others  Commerce  Comm&Mgmt     No         Mkt&HR  56.70
21       F   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin  69.06
22       F   Others   Others   Science   Sci&Tech     No         Mkt&HR  68.81
23       F   Others   Others   Science   Sci&Tech    Yes        Mkt&Fin  63.62
24       M   Others   Others   Science   Sci&Tech     No        Mkt&Fin  74.01
25       F   Others  Central  Commerce  Comm&Mgmt    Yes        Mkt&Fin  65.33
26       M   Others   Others  Commerce  Comm&Mgmt    Yes        Mkt&Fin  57.55
27       M   Others   Others  Commerce  Comm&Mgmt     No         Mkt&HR  57.69
28       M   Others   Others  Commerce  Comm&Mgmt    Yes        Mkt&Fin  64.15
29       M  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin  51.29
..     ...      ...      ...       ...        ...    ...            ...    ...
185      F  Central  Central   Science     Others     No         Mkt&HR  71.43
186      F  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin  62.93
187      M  Central  Central   Science   Sci&Tech    Yes        Mkt&Fin  64.86
188      M   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin  56.13
189      F  Central   Others  Commerce  Comm&Mgmt     No        Mkt&Fin  66.94
190      F   Others  Central  Commerce  Comm&Mgmt     No        Mkt&Fin  62.50
191      M   Others  Central   Science  Comm&Mgmt     No        Mkt&Fin  61.01
192      M  Central  Central  Commerce  Comm&Mgmt    Yes        Mkt&Fin  57.34
193      F  Central  Central      Arts     Others    Yes         Mkt&HR  56.63
194      M   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin  64.74
195      M  Central  Central  Commerce  Comm&Mgmt    Yes         Mkt&HR  58.95
196      M   Others   Others   Science   Sci&Tech    Yes        Mkt&Fin  54.48
197      F   Others   Others   Science   Sci&Tech     No         Mkt&HR  69.71
198      F  Central  Central  Commerce     Others     No         Mkt&HR  71.96
199      M   Others   Others  Commerce  Comm&Mgmt     No         Mkt&HR  55.80
200      M   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin  52.81
201      M  Central   Others   Science  Comm&Mgmt     No         Mkt&HR  58.44
202      M  Central  Central   Science   Sci&Tech     No         Mkt&HR  60.11
203      M   Others   Others  Commerce  Comm&Mgmt     

In [22]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh",OneHotEncoder(),[0,2,4,5,7,8,10])],remainder="passthrough")

In [23]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh",OneHotEncoder(),[0,2,4,5,7,8,10,12])],remainder="passthrough")
# ct = ColumnTransformer([("oh",OneHotEncoder(),[0,2,4,5,7,8,10])],remainder="passthrough")
x = ct.fit_transform(x)

In [24]:
x

array([[ 0.  ,  1.  ,  0.  , ..., 58.  , 55.  , 58.8 ],
       [ 0.  ,  1.  ,  1.  , ..., 77.48, 86.5 , 66.28],
       [ 0.  ,  1.  ,  1.  , ..., 64.  , 75.  , 57.8 ],
       ...,
       [ 0.  ,  1.  ,  0.  , ..., 73.  , 59.  , 69.72],
       [ 1.  ,  0.  ,  0.  , ..., 58.  , 70.  , 60.23],
       [ 0.  ,  1.  ,  1.  , ..., 53.  , 89.  , 60.22]])

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [26]:
x.shape

(215, 23)

In [27]:
x_train[0]

array([ 1. ,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ,  0. ,  1. ,  1. ,  0. ,
        0. ,  1. ,  0. ,  0. ,  1. ,  0. ,  1. , 72. , 60. , 69. , 55.5,
       58.4])

In [28]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# x_train = sc.fit_transform(x_train)
# x_test = sc.fit_transform(x_test)

In [29]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
ypred = mlr.predict(x_test)

In [31]:
ypred

array([324618.08966983,  17179.31614408, 240066.06910854, 302692.50572613,
       341134.75120489,  22028.34990009, 304265.96004619, 249997.81995212,
        38814.02698005,   9091.31917515, 347430.47257186, 266508.21868711,
       277518.78583739, -18346.08739992, 309454.16902071,  28952.40825485,
        26461.82942278, 357601.83060767, 261752.76072773, -42331.90483916,
       351253.28364398, 301038.73802953, 245346.39129779, -68399.06920962,
        19573.84794848, -13246.97876022, 322808.85682328, 324597.22842625,
       373436.85045383, -23190.62856255, 317367.61387007,  63484.51553125,
       -28657.60221028,   7543.1106248 ,  14054.88366   , 250977.82243519,
       279673.38622982,  10682.02063254, 219719.18578216,  28497.08246968,
       342449.85538268, 346551.59461131, 246410.64352754])

In [32]:
y_test

array([270000.,      0., 250000., 250000., 360000.,      0., 236000.,
       300000.,      0.,      0., 250000., 233000., 300000.,      0.,
       265000.,      0.,      0., 280000., 300000.,      0., 400000.,
       240000., 300000.,      0.,      0.,      0., 350000., 240000.,
       360000.,      0., 240000.,      0.,      0.,      0.,      0.,
       265000., 300000.,      0., 230000.,      0., 250000., 200000.,
       250000.])

In [33]:
from sklearn.metrics import r2_score
accuracy = r2_score(ypred,y_test)

In [34]:
accuracy

0.8914962834588992

In [35]:
test = mlr.predict([[ 1.  ,  0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,
        0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  1.  ,
       88.  , 72.  , 78.  , 82.  , 71.43]])

In [36]:
test

array([270194.12135734])

In [37]:
hello = ct.transform([['F',52.58,'Central',54.60,'Central','Commerce',50.20,'Comm&Mgmt','Yes',76,'Mkt&Fin',65.33,'Not Placed']])
# [['F',52.58,'Central',54.60,'Central','Commerce',50.20,'Comm&Mgmt','Yes',76,'Mkt&Fin',65.33,'Not Placed']]

In [38]:
hello

array([[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        1.0, 1.0, 0.0, 1.0, 0.0, 52.58, 54.6, 50.2, 76, 65.33]],
      dtype=object)

In [39]:
test = mlr.predict(hello)

In [40]:
test

array([39664.67812808])